### ISSUE TITLE
Initialize Stadtnavi Project

### ISSUE THREAD

**Issue by md-weber** [stadtnavi/stadtnavi_app#1]
We need the foundation of Trufi to get started.

**Comment by GustavoTCh** [comment]
Which do we need? TruffiCore-Master or https://github.com/trufi-association/trufi-core/pull/420 ?. The bloc package(in pull 20) is a good idea for the project.

**Comment by md-weber** [comment]
I guess we just need a basic flutter application that depends on the GitHub Repository of Trufi Core Master, the bloc pattern is a good idea but we have to make it stable (at the moment there is a problem if you swap the locations)
