### ISSUE TITLE
No Car Route shown in app and the walking route is not shown correctly

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/stadtnavi_app#101]
**Describe the bug**
From: Herrenberg Bahnhof
To: Stuttgart Main Station
Settings: turn off all public transportation options and car sharing options
The following dialog appears (See screenshot 1). 
**Problem 1:** When I click on "Auto Route anzeigen" (Show car route) - no car route is shown but a walking route is shown instead which is very confusing for the user. 
**Problem 2:** The details of the walking route are wrong (See screenshot 2)

Expected: 
- The car route should be shown
- The walking route should not be shown in such long distances (there should be a maximum km for showing walking routes).

**Screenshots**
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/84389152/120249138-26578280-c27a-11eb-8136-9c85aec9fbc3.png)
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/84389152/120249141-29eb0980-c27a-11eb-82b6-676b1cf35ed5.png)

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android
 - Stadtnavi Version 1.1.2

**Comment by samia-roubaa** [comment]
Same issue exists in the iOS app.
iOS 14.4
Stadtnavi app version: 1.1.5

**Comment by GustavoTCh** [comment]
Resolve [Enhance MyModesTransport](https://github.com/trufi-association/trufi-core/pull/492)
