### ISSUE TITLE
Some UI issues / spelling mistakes

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/stadtnavi_app#102]
Here is the list and screenshots will follow: 
Tested on Android App version 1.1.2

1. Side bar on the left: last link should be "Folge uns auf Youtube"
2.  The abbreviation for the day should be followed by only one dot not two
3. German language: decimal separator in kilometer count should be a comma , not a dot. English language the decimal separator is a dot .
4. Time is currently written like this 2 h h 7 min --> correct 2 h 7 min (in many places in the app)
5. Setting a certain address as home address is shown as "Key-Default-Home" -- it should be localized to the chosen language
6. "Key-Default-Work" should also be localized

![grafik](https://user-images.githubusercontent.com/84389152/120249712-0fb22b00-c27c-11eb-835f-2cbf067d4ba1.png)
![grafik](https://user-images.githubusercontent.com/84389152/120249727-180a6600-c27c-11eb-92f7-75ebd84cf607.png)
![grafik](https://user-images.githubusercontent.com/84389152/120249737-1fca0a80-c27c-11eb-811f-784b1a465fd5.png)
![grafik](https://user-images.githubusercontent.com/84389152/120249746-25bfeb80-c27c-11eb-8b15-3667d70045af.png)
![grafik](https://user-images.githubusercontent.com/84389152/120249755-2d7f9000-c27c-11eb-93be-cc390a409bec.png)

**Comment by samia-roubaa** [comment]
Same issues exist in the iOS app
iOS version: 14.4
Stadtnavi app version: 1.1.5
