### ISSUE TITLE
App only suggests one Route

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#104]
Apparently the app was only showing 1 itinerary suggestion while testing. 
![image](https://user-images.githubusercontent.com/63004289/120301945-abb85280-c2cd-11eb-9731-fb20883b782a.png)

I think this is fixed in the current version though. 
![image](https://user-images.githubusercontent.com/63004289/120302208-f33ede80-c2cd-11eb-966b-887d73911957.png)

We will have to change the Icons of the itineraries though. Will happen in a seperate ticket.

**Comment by Denis306** [comment]
@samia-roubaa This is the ticket for the mail Holger sent this morning regarding Ansgars feedback.

**Comment by samia-roubaa** [comment]
@Denis306 could you please forward this mail to me, as I did not receive it.

**Comment by nghanem-poet-egypt** [comment]
@Denis306 there was another problem in the support request: about the CarSharing option not being obvious enough that it is CarSharing. Is there a ticket for this point too?

**Comment by Denis306** [comment]
@nghanem-poet-egypt : This is the ticket for the car sharing icon issue: https://github.com/stadtnavi/stadtnavi_app/issues/106

**Comment by Denis306** [comment]
@nghanem-poet-egypt closing this as it is resolved.
