### ISSUE TITLE
Scaling of the App not working properly

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#108]
On smaller phones like the iPhone SE the icons and the bottom panel are too big and also overlap on some of the information. We need to check that. 

@SamuelRioTz Is there a way you can simulate the usage of an iPhone SE? I took a screenshot but lost it accidentally.

**Comment by SamuelRioTz** [comment]
![simulator_screenshot_355455BC-A712-4245-940E-6834DA027B24](https://user-images.githubusercontent.com/43000324/120425461-418ac680-c33c-11eb-905f-c30fa81ed73a.png)

![simulator_screenshot_6011B5DA-421E-413A-8710-2602CD8816D1](https://user-images.githubusercontent.com/43000324/120425377-0f796480-c33c-11eb-8c2c-5617b634aa87.png)
![simulator_screenshot_6674F21A-E666-4F29-91E2-2BBA8B894BAE](https://user-images.githubusercontent.com/43000324/120425386-156f4580-c33c-11eb-9ba2-9ed674b00776.png)
![simulator_screenshot_3BD9AC8E-B3C3-4F99-A62C-67034395AE9B](https://user-images.githubusercontent.com/43000324/120425407-2324cb00-c33c-11eb-9010-8ab437e1b483.png)

**Comment by SamuelRioTz** [comment]
![simulator_screenshot_9E68681D-DDD9-4B3D-81DF-9FB8ADC10279](https://user-images.githubusercontent.com/43000324/120425625-8f9fca00-c33c-11eb-8979-2af5866299f1.png)
![simulator_screenshot_961AE14B-9B7C-4403-AD1B-4AD7790E6713](https://user-images.githubusercontent.com/43000324/120425636-94647e00-c33c-11eb-8491-7e6b924a8b27.png)
