### ISSUE TITLE
Update Feedback Option according to stadtnavi

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#11]
The stadtnavi feedback function sends the user to the feedback form (https://stadtnavi.de/feedback/) in a new window.
![image](https://user-images.githubusercontent.com/63004289/116930309-e3e15c80-ac5f-11eb-8aa2-b4737c63d4e8.png)

In Trufi we have the Feedback function available, but it opens up the email program of the user and puts in the email adress and subject if you click on the "mail" button on the lower right corner.
![image](https://user-images.githubusercontent.com/63004289/116930774-7a158280-ac60-11eb-8b0e-7cb975f01482.png)

@leonardehrenfried do you want us to prompt the user out of the app to the feedback form (https://stadtnavi.de/feedback/) or do you want us to implement the feedback form so it is displayed in the app.

**Comment by Denis306** [comment]
@hbruch @leonardehrenfried Do you want us to implement the feedback form in the app as new panel, or do you want us to simply link to the feedback form you have set up for stadtnavi already?

**Comment by Denis306** [comment]
@GustavoTCh We just want to link out of the app to the feedback form -> https://stadtnavi.de/feedback/

**Comment by GustavoTCh** [comment]
Ok 👍

**Comment by GustavoTCh** [comment]
https://github.com/trufi-association/trufi-core/pull/453  is the PR in trufi-core

Preview:

https://user-images.githubusercontent.com/42806689/117445523-c682eb80-af08-11eb-8153-8cbd25882eec.mov

**Comment by md-weber** [comment]
I guess we need to update the Screen Text for Stadtnavi, right? So we would probably need a custom translation for that. `Please e-mail us` is not a good headline for a Form. 🤔
