### ISSUE TITLE
"Use Carpool" Feature

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#114]
We need to implement the mode CARPOOL in the frontend the same way like BIKE, PARK, etc. so we can use the information we get from the backend.

CARPOOL is also treated same as public transport.

Example:  BUS, TRAIN, CARPOOL

@leonardehrenfried please correct me if I'm wrong on anything.

**Comment by Denis306** [comment]
@SamuelRioTz Maybe you can look into this ticket to see how exactly they are fetching the offered car pools to show them in the itirenaries. https://github.com/stadtnavi/digitransit-ui/issues/535

**Comment by GustavoTCh** [comment]
implemented in https://github.com/trufi-association/trufi-core/pull/559
