### ISSUE TITLE
On demand Taxi Feature

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#120]
All the needed information is here: https://github.com/stadtnavi/digitransit-ui/issues/350

**Comment by GustavoTCh** [comment]
Adding demand taxi feature in https://github.com/trufi-association/trufi-core/pull/498

**Comment by GustavoTCh** [comment]
New TaxiPlan

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-09 at 17 14 58](https://user-images.githubusercontent.com/42806689/121382028-83bc9500-c946-11eb-911f-7862593dd969.png)

Data of taxiPlan

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-09 at 17 11 33](https://user-images.githubusercontent.com/42806689/121382042-861eef00-c946-11eb-80ba-0266387aaca4.png)

**Comment by GustavoTCh** [comment]
Changes in UI

![196859934_394914588424335_3149743011058377156_n](https://user-images.githubusercontent.com/42806689/121404358-2cc1ba80-c95c-11eb-8376-fa5d92c9c99a.jpg)

If there is a bookinUrl set in graphql response UI will look like that:

![194261113_3427612064008953_1588208112772998866_n](https://user-images.githubusercontent.com/42806689/121404340-2a5f6080-c95c-11eb-8889-f4bca6554252.jpg)
