### ISSUE TITLE
Display Fares (Ticketing)

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#121]
Info here: https://github.com/stadtnavi/digitransit-ui/issues/352

It is already on dev but missing one small UI implementation (see Leonards last comment): https://dev.stadtnavi.eu/reiseplan/Nufringen%3A%3A48.6224388%2C8.8881021/Ehningen%3A%3A48.6592556%2C8.9405097/0?time=1623915089

**Comment by GustavoTCh** [comment]
Fares screens:

- With available fare

WebApp
![Screen Shot 2021-06-18 at 10 52 07](https://user-images.githubusercontent.com/42806689/122536635-08817000-d025-11eb-8140-b7076676fe84.png)

MobilApp
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-18 at 10 51 58](https://user-images.githubusercontent.com/42806689/122536647-0b7c6080-d025-11eb-812a-d5580d9427a1.png)

- With fare not available

WebApp
![Screen Shot 2021-06-18 at 10 56 22](https://user-images.githubusercontent.com/42806689/122536816-3961a500-d025-11eb-8fe8-8924ccd95003.png)

MobilApp
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-18 at 10 56 27](https://user-images.githubusercontent.com/42806689/122536891-4aaab180-d025-11eb-8ad0-00bddc161cc8.png)

- With warning for sharing

WebApp
![Screen Shot 2021-06-18 at 10 49 39](https://user-images.githubusercontent.com/42806689/122538331-b9d4d580-d026-11eb-9515-569df48f2a6e.png)

MobilApp
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-18 at 10 49 25](https://user-images.githubusercontent.com/42806689/122538337-bb9e9900-d026-11eb-8294-919e18d5f175.png)

**Comment by GustavoTCh** [comment]
PR https://github.com/trufi-association/trufi-core/pull/523

**Comment by nghanem-poet-egypt** [comment]
Comments to be solved: 
1. In German language: the price needs to have a comma , as decimal separator not a dot .
In English language: it should stay a dot

2. The button "Tickets kaufen" doesn't link to anything, it should have a link in the background or get removed --> In the ticket https://github.com/stadtnavi/digitransit-ui/issues/352 it is written to "Only display the "Book" button when the backend sends the URL."

![grafik](https://user-images.githubusercontent.com/84389152/122739567-67442500-d283-11eb-97dc-d1dfe6ce5299.png)
