### ISSUE TITLE
Wrong bicycle symbol/text in journey overview

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/stadtnavi_app#127]
**Describe the bug**
Journey overview shows bikesharing symbol/color and untranslated "Bicycle"

**To Reproduce**
1. Plan route from Vaihingen Schillerplatz to Feuersee Stuttgart
2. Switch to bicycle mode
3. See screen like the one below

**Expected behavior**
* Journey overview should be rendered like web version, i.e. correct icons should be used and text translated
* Leg color does not match web color but uses biksharing color
* Bike symbols should not cover important parts of the map

**Screenshots**
<img width="318" alt="grafik" src="https://user-images.githubusercontent.com/2187389/120915493-4042fc00-c6a4-11eb-9040-51811f912a74.png">

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS14.4.2
 - Version 22

**Comment by Denis306** [comment]
Closing this as it is resolved.
