### ISSUE TITLE
Route suggestion shows walking first although Transit route is found

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/stadtnavi_app#129]
From Hauptstraße
To Seniorenzentrum Widenhöfer-Stift

Current behavior: 
The first suggested route is a walking route which is too long 1h 6 min
The second suggested route has a transit in it and a lot less walking

Expected: the transit route should have been showed first. 

1. Walking route
![grafik](https://user-images.githubusercontent.com/84389152/121012889-79f52f00-c798-11eb-971e-2427f7cc87eb.png)

2. Transit route
![grafik](https://user-images.githubusercontent.com/84389152/121012934-86798780-c798-11eb-9fc9-eceae1e34359.png)

**Comment by GustavoTCh** [comment]
@nghanem-poet-egypt, New versions have already solved these problems.

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-28 at 14 30 46](https://user-images.githubusercontent.com/42806689/123636850-a2170180-d81d-11eb-9b6d-cae1d077d046.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-28 at 14 30 39](https://user-images.githubusercontent.com/42806689/123636871-a5aa8880-d81d-11eb-8565-8156c4bd1b31.png)
