### ISSUE TITLE
Clima Indicator

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#13]
The stadtnavi web app has a component that shows the clima once you put in a route. 
![image](https://user-images.githubusercontent.com/63004289/116903557-dbc3f580-ac3c-11eb-926f-e44900760fc7.png)

It might not be working properly right now but I think it would be a nice option to have it in the app. We don't know where yet but we need the functionality.

**Comment by md-weber** [comment]
The Flutter version upgrade currently blocks this Issue. In Flutter 2.0, we are unable to access the API endpoints for OpenWeatherMap & FMI.

More details can be found here: https://github.com/trufi-association/trufi-core/pull/474

**Comment by md-weber** [comment]
Checked on an intel based chip there I did not have the issues. The issue is unblocked.
