### ISSUE TITLE
Station names are the same in begin and end station

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/stadtnavi_app#130]
**Describe the bug**
- The shown station names are wrong the begin and end station are the same names
- Not only the station names but also street names by car or by bike are the same 

**To Reproduce**
From: Hauptstraße
To: Seniorenzentrum Wiedenhöfer-Stift
The begin and end stations of the bus have the same names

**Expected behavior**
The correct names should be shown

**Screenshots**
![grafik](https://user-images.githubusercontent.com/84389152/121014769-a0b46500-c79a-11eb-8b2a-f553729fc7d0.png)

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 11
 - App: Version 1.1.6

**Comment by md-weber** [comment]
This bug seems to be resolved already 👍 could you double-check @nghanem-poet-egypt?

**Comment by nghanem-poet-egypt** [comment]
Yes it's solved
