### ISSUE TITLE
No later and earlier departure

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#133]
There is no later and earlier departure buttons with the transit modes like the webapp

We should add the two buttons : earlier departures and later departures

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/84456072/121018192-75cc1000-c79e-11eb-9fd8-bfee16730ab0.png)

**Comment by GustavoTCh** [comment]
Implemented in https://github.com/trufi-association/trufi-core/pull/557

https://user-images.githubusercontent.com/42806689/123982220-2060d880-d9c3-11eb-952d-d2642cae2892.mov
