### ISSUE TITLE
Error occur when requesting multiple routes at the same time

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#135]
**Describe the bug**
Error occur when requesting multiple requests within a short time period
**To Reproduce**
1) Request any route
2) While loading the first route quickly select the time dropdown and click leaving now
3) The app will request a new route
4) Do that multiple times
5) The app will show an error

**Expected behavior**
To fetch the last route requested normally
**Screenshots**
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/84456072/121048265-f0a12500-c7b6-11eb-98d4-54ff842e6f41.png)

**Smartphone**
 - Device: Android

**Additional context**
Also the error message shown is written twice "Canceled by user. Canceled by user."

**Comment by GustavoTCh** [comment]
@ahmed-nawar The problem is solved in the new versions (>=1.3.5)
