### ISSUE TITLE
Cannot report feedback

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#136]
**Describe the bug**
Cannot report feedback
**To Reproduce**
1. Open the app
2. Click on the report feedback button or choose any route then click on the report feedback button
3. If you didn't give permissions, the app will ask you for permissions
4. The error appears

**Expected behavior**
To be able to submit the feedback when you click on the feedback button anywhere in the app
**Screenshots**
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/84456072/121049214-cbf97d00-c7b7-11eb-8ed3-2c1ca0c67513.png)

**Smartphone:**
 - Device: Android

**Additional context**
This issue happens anywhere in the app

**Comment by Denis306** [comment]
@ahmed-nawar could you please double check again? This issue should be solved.

**Comment by ahmed-nawar** [comment]
@Denis306 So from what I can see, the `Report Defect` button has been removed and the user can report a defect from the settings menu. Is that correct?

**Comment by Denis306** [comment]
@ahmed-nawar Yes.

**Comment by ahmed-nawar** [comment]
![MicrosoftTeams-image (23)](https://user-images.githubusercontent.com/84456072/122957992-c046b280-d382-11eb-913e-6a31c19c8214.png)
Cannot report defect on Android v1.2.9

**Comment by Denis306** [comment]
@SamuelRioTz Can you please check this.

**Comment by SamuelRioTz** [comment]
FIXED: this issue was only for android >29, extra config was needed
