### ISSUE TITLE
Why show a car route for a short distance

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#137]
**Describe the bug**
When the distance is very short a car/bike/park & ride routes are shown
**To Reproduce**
1. Place the origin and destination markers on top of each other
2. Check the routes returned

**Expected behavior**
Only walking routes should be returned for very short routes
If the user selects the same address as the origin and destination, a message should be shown "Please select a different destination" for example
**Screenshots**
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/84456072/121049801-55a94a80-c7b8-11eb-9d73-28cf720eeb42.png)

**Smartphone:**
- Android

**Comment by GustavoTCh** [comment]
The modifications are already in the new version (>=
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-28 at 15 02 39](https://user-images.githubusercontent.com/42806689/123641182-4602ac00-d822-11eb-8141-da767ea3992c.png)
1.3.5).
