### ISSUE TITLE
The transit icons in a route size is not proportional with the map

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#138]
**Describe the bug**
The bus/car/train/subway icons size doesn't collapse or get smaller in size when the map is zoomed out
**To Reproduce**
1. Choose origin and destination which returns a transit in the routes
2. Zoom out
3. Check transit icon in the returned route

**Expected behavior**
The icons should get smaller just like the other icons and disappear when the user zooms out
**Screenshots**
![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/84456072/121053080-47106280-c7bb-11eb-98c6-d86dcf66d271.png)

![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/84456072/121052675-e4b76200-c7ba-11eb-881e-58230e153794.png)

**Smartphone:**
 - Device: Android

**Comment by Denis306** [comment]
The transit icons got removed from the itinerary lines.
