### ISSUE TITLE
Add Leaving and Arrival Times to Itinerary suggestions

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#14]
The Itinerary in Trufi needs to be enhanced with some more information.
Since you can choose the custom departure time, you will also be able to choose between different itineraries. 
![image](https://user-images.githubusercontent.com/63004289/116910295-ba1b3c00-ac45-11eb-9328-a44a51df8e85.png)

This ticket needs to be implemented after the mode settings panel https://github.com/stadtnavi/stadtnavi_app/issues/8.

**Comment by GustavoTCh** [comment]
[Itinerary details](https://github.com/trufi-association/trufi-core/pull/476) This PR is in TrufiCore
