### ISSUE TITLE
No scrollbar in the map layers menu

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#143]
**Describe the bug**
When I click on the map layer button on the top right of the screen, a list menu appears with only 5 check boxes(Roadworks, Bus stops, Train stations, carpool stops, metro station), but the list is longer than that. The normal user might think that these 5 check boxes are the only options in the list whilst there are more to select from.
**To Reproduce**
1. Go to stadtnavi android app
2. click on the terrain icon button
3. check the shown options checkboxes

**Expected behavior**
There should be a scroll bar to show the user that there are more options
There should be an indicator (different color or a bottom border) to differentiate between the map icons sections and the map layers section
**Screenshots**
![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/84456072/121192201-fb1df600-c86c-11eb-8bbc-06da199b9d6c.png)

**Smartphone:**
 - Device: Android

**Comment by nghanem-poet-egypt** [comment]
Can this bar also have a close icon as reported from the users?

**Comment by Denis306** [comment]
Closing this as this is an issue that was reported on the old UI. 
The new issue is this one: https://github.com/stadtnavi/stadtnavi_app/issues/169
No more close icon is needed but the scroll bar is still missing.
