### ISSUE TITLE
Map locked while viewing info cards

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#144]
**To Reproduce**
1. Show the map icons of parking, charging stations
2. click on any icon to view information about them
3. Try to move around the map by dragging it

**Expected behavior**
User should be able to move around the map while viewing any info card
**Screenshots**
![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/84456072/121194352-f65a4180-c86e-11eb-9678-02f9602396bc.png)
![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/84456072/121194381-fa865f00-c86e-11eb-8b1d-bdadbc2c4a07.png)

**Smartphone:**
 - Device: Android

**Comment by nghanem-poet-egypt** [comment]
Same thing happens if a route is open in the bottom

**Comment by Denis306** [comment]
@nghanem-poet-egypt can you test this again please? Should be fixed.

**Comment by nghanem-poet-egypt** [comment]
@Denis306 the map is not locked anymore when an info card is oen I can move around and zoom in the map but the POIs are not clickable when an itenerary is shown. Is that the expected behavior?

**Comment by Denis306** [comment]
@nghanem-poet-egypt Good. I would suggest closing this ticket then please and create a new one for the other issue. That way we can prioritize them accordingly. I talked to Samuel about it and it seems more complex which is why it is not implemented yet.

**Comment by Denis306** [comment]
Closing this issue and created a new one for the discussed topic: #259
