### ISSUE TITLE
The bottom panel info card should be resizable to full screen

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#147]
**Describe the bug**
To have a more user friendly interface and be able to view the info card more comfortably.
To be able to drag the bottom panel info card to resize it as the user desires
**To Reproduce**
1. Enable icons on map 
2. Click on any icon (parking, charging station... etc.) to view info about it
3. Try to resize the panel

**Expected behavior**
To be able to drag the bottom panel header and resize it to be full screen
**Screenshots**
![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/84456072/121215389-3e359480-c880-11eb-8d6b-7d8c64da6b1f.png)

**Smartphone:**
 - Device: Android

**Additional context**
https://github.com/stadtnavi/stadtnavi_app/issues/64

**Comment by ahmed-nawar** [comment]
Also the resizing should be handled by dragging the header not using the arrow up/down button

**Comment by Denis306** [comment]
@ahmed-nawar can you recheck and close this please? I think it is fixed.

**Comment by Denis306** [comment]
This issue is fixed.
