### ISSUE TITLE
Modify default Favorites

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#16]
Currently, under "your places" (Favorites), there are two places displayed per default.
![image](https://user-images.githubusercontent.com/63004289/116907385-c604ff00-ac41-11eb-867b-2c49f8aae78c.png)
<img width=200 src="https://user-images.githubusercontent.com/63004289/116907875-7c68e400-ac42-11eb-9d41-a2385d762a9a.png">

It would be better to change these default places to the following if they were not edited by the user already:
"Home" -> "Add Home"
"Work" -> "Add Work"

So if you click on it and it is not yet configured you will be asked to edit it.

**Comment by GustavoTCh** [comment]
https://github.com/trufi-association/trufi-core/pull/455 this is the PR in Trufi-Core
