### ISSUE TITLE
Routing takes considerably longer than in the web app

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#160]
Apparently the mobile apps takes way more time to load the routing suggestions than the web app. Please do some investigation on what possible causes could be.

**Comment by Denis306** [comment]
@samia-roubaa This issue is connected to #171. We split up the loading of results. So please check again and report back if there was an improvement.

**Comment by nghanem-poet-egypt** [comment]
@Denis306 replying to your previous comment about #171 I've tested this issue and closed it. Was there something else done to improve the speed and needs testing or should I close this issue as well?

**Comment by Denis306** [comment]
@nghanem-poet-egypt No, that was the main reason why the mobile app took longer to load results than the web app. You can close this.
