### ISSUE TITLE
"Walking" Routing suggestion should not be shown if the walk is too long

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#161]
The routing suggestions are currently not working like in the web app. If you search the route "Gültstein" to "Schönbuchturm" the app suggests the walking route that takes 1h 17 min.
![image](https://user-images.githubusercontent.com/63004289/121819719-e9828700-cc8e-11eb-93fe-c5bf65e7e37c.png)

If you look for the same route in the web app it does not suggest that.
![image](https://user-images.githubusercontent.com/63004289/121819727-f3a48580-cc8e-11eb-8906-9d87199d1b3a.png)

The routing suggestions have to be the same like in the web app. Something is not working quite right.

**Comment by GustavoTCh** [comment]
Resolve in https://github.com/trufi-association/trufi-core/pull/538

![WhatsApp Image 2021-06-23 at 2 02 51 PM](https://user-images.githubusercontent.com/42806689/123093370-e6745d00-d42b-11eb-8dc4-51afe612db51.jpeg)
