### ISSUE TITLE
Missing Infobox when all search settings are turned off

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#162]
When all the search settings are turned off in the webapp when looking for walking routes, it does not display any modes. Instead, it displays a box with an informational text and a suggestion of different routes of different modes.
![image](https://user-images.githubusercontent.com/63004289/121820254-23a15800-cc92-11eb-98b9-f2d4558a5b7e.png)

The mobile app on the other hand will always display the walking mode although the routes suggested are the same as in the web app.
![image](https://user-images.githubusercontent.com/63004289/121820263-3451ce00-cc92-11eb-85ab-0ca5570b1730.png)

Please add the Info box as in the web app and make sure the same logic around walking mode routes is used in the mobile app like in the web app.

**Comment by GustavoTCh** [comment]
resolved in https://github.com/trufi-association/trufi-core/pull/536
