### ISSUE TITLE
Availability check marks are not working like in the web app

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#163]
The web app uses check marks in green, a clock in orange and a cross in red to indicate the availability of parking garages.
![image](https://user-images.githubusercontent.com/63004289/121821023-649b6b80-cc96-11eb-9584-9fcbf15e1be5.png)

The mobile app is currently only displaying the green check marks. 
![image](https://user-images.githubusercontent.com/63004289/121821020-5e0cf400-cc96-11eb-8d6b-fc589891747b.png)

Please change this to be the same behaviour as in the web app.

**Comment by Denis306** [comment]
@leonardehrenfried could you please provide some context to @SamuelRioTz on when the availability should be green, orange, red? Thank you!

**Comment by SamuelRioTz** [comment]
@Denis306  the real issue here comparing web with app, is that on the web the map layers is fetched every interaction and in the app the map layer is fetched only once at the first time.
@leonardehrenfried there is some how to get the updated marker state individually? another workaround could be force re-fetch every some time. e.g. 1 min

**Comment by leonardehrenfried** [comment]
Sorry for the late answer:

you can use the following GraphQL query:

```
query parking {
  vehicleParking(id: "OSM:OSMWay/39040154") {
    vehicleParkingId
    name
    lon
    lat
    capacity {
      carSpaces
      bicycleSpaces
      wheelchairAccessibleCarSpaces
    }
    availability {
      carSpaces
      bicycleSpaces
      wheelchairAccessibleCarSpaces
    }
    imageUrl
    tags
    anyCarPlaces
    detailsUrl
    note
    openingHours
  }
}
```

**Comment by leonardehrenfried** [comment]
Or you can redownload the tiles every x seconds.
