### ISSUE TITLE
When a route is suggested, zoom out as far as necessary to be able to see the whole itinerary

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#166]
When searching for a route and you get a suggestion the map should be zoomed out far enough so you can see the whole itinerary at once.

- [x] Add a little margin/padding to the crop function so the route is better visible.

**Comment by ahmed-nawar** [comment]
When the bottom itineraries drawer is minimized, the map is zoomed out reasonably after I click on an itinerary.
![IMG-9625](https://user-images.githubusercontent.com/84456072/122916537-49e38980-d35d-11eb-8072-bbe9b5098462.PNG)
---

When the bottom panel is maximized and I click on an itinerary, the map is zoomed out too much after I minimize the panel to view the route.
![IMG-9623](https://user-images.githubusercontent.com/84456072/122916526-4819c600-d35d-11eb-97f2-321b4b8f2bcf.PNG)
![IMG-9624](https://user-images.githubusercontent.com/84456072/122916543-4bad4d00-d35d-11eb-98cd-ad39c7caaa5b.PNG)

**Comment by Denis306** [comment]
@SamuelRioTz Reopening so we can solve this.
