### ISSUE TITLE
Translation missing in car itinerary overview

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#167]
Even though the language is set to german the itinerary overview says "CAR".
![image](https://user-images.githubusercontent.com/63004289/121822275-8bf63680-cc9e-11eb-9120-0291e3e32199.png)

It should also be "Fahren" as described in following issue: https://github.com/stadtnavi/digitransit-ui/issues/624

**Comment by Denis306** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/63004289/121902241-6f521100-cd27-11eb-8c1e-f728c78d9cfb.png)

**Comment by nghanem-poet-egypt** [comment]
Issue tested and is ok
