### ISSUE TITLE
Time notation wrong in car pool offering screen

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#168]
Although the language is set to german the time is being displayed in english notation (AM/PM)
![image](https://user-images.githubusercontent.com/63004289/121822336-ec857380-cc9e-11eb-88c6-0f4ac40339b1.png)

Please change it so it displays the german notation of time (00:00 Uhr - 24:00 Uhr)

**Comment by nghanem-poet-egypt** [comment]
1. The localisation is fixed when German language is chosen but is now wrong in English 
--> in English it is 15:30 hrs now - expected 03:30 PM like the old state 

2. On the next page when the carpool is saved the clock and date are correct in English but wrong in German. 
--> expected: clock in German format when locale is German and date also in the format 01.01.2021 dd.mm.yyyyy separated by . not /

**Comment by GustavoTCh** [comment]
Germany:
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-18 at 12 00 02](https://user-images.githubusercontent.com/42806689/122544319-fd324280-d02c-11eb-956d-f330ee0659f0.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-18 at 12 00 13](https://user-images.githubusercontent.com/42806689/122544339-00c5c980-d02d-11eb-91a0-b430079814ca.png)

English:
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-18 at 12 00 35](https://user-images.githubusercontent.com/42806689/122544402-120ed600-d02d-11eb-8852-238d1a520386.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-18 at 12 00 46](https://user-images.githubusercontent.com/42806689/122544409-15a25d00-d02d-11eb-9356-8765d02f79dc.png)

**Comment by ahmed-nawar** [comment]
In the page where the carpool is saved, date format is incorrect in German.
-> Expected: Date in the format 01.01.2021 dd.mm.yyyyy separated by . not /

![date](https://user-images.githubusercontent.com/84456072/122677390-614a3780-d1e2-11eb-886f-c48e0186e85d.jpg)
