### ISSUE TITLE
Add scroll bars to the scrollable items

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#169]
Scrollable items currently don't have a scroll bar fading in (iOS).
![image](https://user-images.githubusercontent.com/63004289/121822563-070c1c80-cca0-11eb-9041-809c5fb554d2.png)

Add a scroll bar to the scrollable items like in the following screenshot:
![image](https://user-images.githubusercontent.com/63004289/121822570-10958480-cca0-11eb-89e9-7221061c47af.png)

**Comment by ahmed-nawar** [comment]
- In the map layers menu the scroll bar is shown when you scroll but disappears when you're not scrolling for a few seconds. Is this the required behavior?[IOS]
- In the bus stop details there is not a scroll bar in both the Right Now tab and the Timetable tab
![busstop](https://user-images.githubusercontent.com/84456072/122398796-82a8ea80-cf7a-11eb-92e4-9948f477777f.png)

**Comment by Denis306** [comment]
@ahmed-nawar Did you update to the current version of the beta app? 
Android: v1.2.5(34)
iOS: v1.2.5(34)

Yes, the behavior of the scroll bar disappearing is intended. 

The scroll bars are in the "right now" and also in the "timetable" tab:
![image](https://user-images.githubusercontent.com/63004289/122400064-a7519200-cf7b-11eb-8955-a6e291ed61cb.png)
![image](https://user-images.githubusercontent.com/63004289/122400201-ca7c4180-cf7b-11eb-8ace-03547c54b000.png)

Closing this issue.

**Comment by Denis306** [comment]
@SamuelRioTz missing in Android. Or is it in the internal version already?

**Comment by ahmed-nawar** [comment]
@nghanem-poet-egypt Can you validate this on android please?
