### ISSUE TITLE
Translations in Park & Ride mode are missing

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#170]
The translation of the itinerary description in Park & Ride mode are missing:
![image](https://user-images.githubusercontent.com/63004289/121822713-d5e01c00-cca0-11eb-8e13-e31c73434127.png)

- [x] This is what it should look like:

![image](https://user-images.githubusercontent.com/63004289/121822755-0b850500-cca1-11eb-976f-d02978778b4f.png)

- [x] Also, please implement the blue "P+Car" Icon to indicate the parking process

**Comment by GustavoTCh** [comment]
Done in PR https://github.com/trufi-association/trufi-core/pull/512

**Comment by nghanem-poet-egypt** [comment]
Issue tested and is ok
