### ISSUE TITLE
All routing results are being returned at the same time

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#171]
Currently, the app loads all itinerary suggestions at the same time and takes quite long to return any results.

Compared to that, the web app first loads and displays the transit mode and loads the alternative suggestions afterwards.

If possible, please make it load the suggestions that way as well.

**Comment by GustavoTCh** [comment]
Done:
- I separate the queries
- The graphql query cache has been improved

incomplete:
- Enhance loading for alternative suggestions 

https://user-images.githubusercontent.com/42806689/121889443-8853c580-cd19-11eb-8c34-af601889ed1c.mov

**Comment by nghanem-poet-egypt** [comment]
Splitting the queries has improved the speed of showing the default results.
