### ISSUE TITLE
Bike & Ride Mode window is named "Fahrrad"

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#172]
If you click on the Bike & Ride mode and get to the window with the Bike & Ride suggestions the header says "Fahrrad"
![image](https://user-images.githubusercontent.com/63004289/121822901-007ea480-cca2-11eb-9258-e39484fa8df7.png)

Please change the header to say "Bike & Ride"

**Comment by GustavoTCh** [comment]
Done in PR https://github.com/trufi-association/trufi-core/pull/512

**Comment by nghanem-poet-egypt** [comment]
@Denis306 is "Bike and Ride" also accepted if the app is viewed in German? Or should it be translated? Same question applies to Park & Ride. 

I compared it with the we but there is no title there just a hint "Fahrrad abstellen und weiterfahren"

**Comment by Denis306** [comment]
@nghanem-poet-egypt In general we also say "Park & Ride" in german, so I would also think "Bike & Ride" would be fine. As you switch screens when clicking on one of the "mode tiles" we implemented the title/name of that mode for the user to always know what status the app is in/ which mode he is looking at. 

So I would say: Yes this is intended. Maybe @leonardehrenfried or @hbruch can approve.

**Comment by Denis306** [comment]
@nghanem-poet-egypt this can be closed as we renamed it to "Bike & Ride" to avoid translation conflicts.
