### ISSUE TITLE
"Map Layer Switcher" Button disappears in Landscape mode

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#175]
The "Map Layer Switcher" Button disappears under the "center map" button.
![image](https://user-images.githubusercontent.com/63004289/121895302-5b56e100-cd20-11eb-8b6f-8c4b0f0e1071.png)

**Comment by nghanem-poet-egypt** [comment]
Issue still happens on Android but the other way around the "center" button gets hidden behind the report issue button. Not only on landscape but also on portrait mode

![tmp_1623942677469.jpg](https://user-images.githubusercontent.com/84389152/122426225-5a2beb00-cf90-11eb-8982-5a23cc1fe0db.jpg)

**Comment by ahmed-nawar** [comment]
While in route mode, the expand route button disappears in two cases
1. Portrait mode and expand the itineraries list 
2. Landscape mode

![IMG-9542](https://user-images.githubusercontent.com/84456072/122400711-41b1d580-cf7c-11eb-932e-a3554a14b3c1.PNG)
![IMG-9541](https://user-images.githubusercontent.com/84456072/122400719-44142f80-cf7c-11eb-9453-db06db5ba1cb.PNG)

**Comment by Denis306** [comment]
@ahmed-nawar this is the old version please test again on the current version and close this issue. This should be fixed.
