### ISSUE TITLE
Adapt Colors of Bus Lines according to Stadtnavi Branding

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#18]
Currently the colors of the routes are all pink. 
![image](https://user-images.githubusercontent.com/63004289/116861846-19585c80-ac04-11eb-8914-cf0c11deeb72.png)

Stadtnavi uses different colors for the different transportation types though: 
![image](https://user-images.githubusercontent.com/63004289/116861940-3e4ccf80-ac04-11eb-8512-6cb536dc0cee.png)

The walking parts are usually displayed in grey. 

The Icons in the searchbar of the Trufi app are also different to the ones in stadtnavi.

**Comment by GustavoTCh** [comment]
I changed the color of the route, but I don't found the icons. @Denis306 Do You Know where I can find the assets?
 
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-05-14 at 12 52 55](https://user-images.githubusercontent.com/42806689/118305510-125c0480-b4b6-11eb-89a4-d03670c44eff.png)
