### ISSUE TITLE
Feedback User 250: remove the decimal places from the weather 

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/stadtnavi_app#181]
The weather temperature should be displayed as an integer. Please remove the decimal places. 

![image](https://user-images.githubusercontent.com/84382750/121914829-ee007b80-cd32-11eb-87eb-533aea5e1fa2.png)

**Comment by GustavoTCh** [comment]
implemented in https://github.com/trufi-association/trufi-core/pull/554

![WhatsApp Image 2021-06-29 at 11 48 45 AM](https://user-images.githubusercontent.com/42806689/123828958-04c8d580-d8d0-11eb-9376-fbe824e9398f.jpeg)
