### ISSUE TITLE
Feedback User 254: roadblocks and bus routes have the same color 

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/stadtnavi_app#184]
The priority of this bug: 4

It's confusing for the user that both, roadblocks and bus routed have the same color. One of them should be changed. 

![image](https://user-images.githubusercontent.com/84382750/121917685-a92a1400-cd35-11eb-9ff6-4ce235115ba0.png)

**Comment by Denis306** [comment]
@hbruch is this something we should consider? We had this feedback regarding the color of the road blocker lines from a few users. Should we make them transparent or doted line or something? Or leave it as it is.

**Comment by hbruch** [comment]
Could you reduce width and try a dashed style (e.g. using white/red strokes) for the road works

**Comment by Denis306** [comment]
Hi @hbruch, I just talked to Samuel and he thinks that would take some more effort. So the options are:
1. Do some research on how to implement the red\white dashed line
2. simply make it a dotted red line.

What do you think?

**Comment by hbruch** [comment]
Let's start with a dotted red line, if that works well for app and web

**Comment by SamuelRioTz** [comment]
@hbruch 
red with 80% opacity
![image](https://user-images.githubusercontent.com/43000324/123594782-20dc5200-d7be-11eb-81bb-86304e1314ef.png)
grey with 80% opacity
![image](https://user-images.githubusercontent.com/43000324/123594745-1621bd00-d7be-11eb-90ba-230ca8902791.png)

**Comment by Denis306** [comment]
@SamuelRioTz let's go with the red dotted line. Looks good I think.

**Comment by MartinH-open** [comment]
thanks for working on my request.
BTW - the start and end circles look very much like a bus stop circle. Perhaps change the sign here to something like the traffic sign.  "Do not enter" "Durchfahrt verboten"  oder "Einfahrt verboten"
![image](https://user-images.githubusercontent.com/1383111/123651901-22dcfa00-d82c-11eb-9dc7-a5e81c8f2970.png)

**Comment by SamuelRioTz** [comment]
![image](https://user-images.githubusercontent.com/43000324/123678318-29f80e00-d814-11eb-9961-66bdb7988657.png)
