### ISSUE TITLE
Feedback User 256: wrong itinerary details

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/stadtnavi_app#185]
The android app sometimes displays "Ihr Standort" as the origin and the destination of the user. 
![image](https://user-images.githubusercontent.com/84382750/121918768-aaa80c00-cd36-11eb-966a-bb0f6747c2fc.png)
![image](https://user-images.githubusercontent.com/84382750/121918907-c9a69e00-cd36-11eb-8caf-41d2d9f333c3.png)

**Comment by Denis306** [comment]
@sara-georgy could you please test this again? This was an old version. Should not happen anymore. The current version is 1.3.2
