### ISSUE TITLE
The route returns wait then walk legs

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#190]
**Describe the bug**
The route returns a wait leg then walk leg which doesn't make sense. Also the webapp returns different results
**To Reproduce**
1. Origin: Stuttgart Main Station
2. Destination: Stuttgarter Strasse
3. Time: 23:00
4. Choose the Taxi mode
5. First itinerary

**Expected behavior**
To return a logical route with logical legs
**Screenshots**
![waitthenwalk](https://user-images.githubusercontent.com/84456072/122040776-87359d80-cdd8-11eb-875c-4d5cf0e7161b.jpg)
![image](https://user-images.githubusercontent.com/84456072/122040962-b815d280-cdd8-11eb-9980-d2694c376d90.png)

**Smartphone:**
 - Device: IOS

**Comment by GustavoTCh** [comment]
@ahmed-nawar  

We show the wait when there is a time difference between the rest of the elements (walking, bicycle, bus, train ...), if we look at the web application, walking = 2min but differences between transports is 5 minutes

![122040962-b815d280-cdd8-11eb-9980-d2694c376d90](https://user-images.githubusercontent.com/42806689/123656103-e90df280-d82f-11eb-9b4c-ded3d715e368.png)


We currently show the separator between walk and wait items:

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-28 at 16 31 17](https://user-images.githubusercontent.com/42806689/123654364-4bfe8a00-d82e-11eb-9475-db41fe426f3a.png)

**Comment by ahmed-nawar** [comment]
Thanks for the clarification. Adding the separator is a great idea.
