### ISSUE TITLE
Change "About" section

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#191]
- [ ] Please delete the Trufi part in the About section.

![image](https://user-images.githubusercontent.com/63004289/122043924-3162f480-cddc-11eb-93d7-9354360638a6.png)

- [ ] Also, please change the text in the "about this service" / "Über diesen Service" section to the following:

German:
stadtnavi ist eine Reiseplanungs-Anwendung für die Stadt Herrenberg und Umgebung. Dieser Dienst umfasst ÖPNV, Fußwege, Radverkehr, Straßen- und Parkplatzinformationen, intermodales Routing, Ladeinfrastruktur und Sharing-Angebote.

English:
stadtnavi is a travel planning application for the city of Herrenberg and its surroundings. This service includes public transport, footpaths, cycling, street and parking information, intermodal routing, charging infrastructure and sharing offerings.

**Comment by nghanem-poet-egypt** [comment]
Issue is OK
