### ISSUE TITLE
Replace Park & Ride Icon in the Settings and disable taxi, car sharing and cargo bike settings invisible

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#195]
Info is here: https://github.com/stadtnavi/digitransit-ui/issues/640

This is the icon: 
[car-train-1.zip](https://github.com/stadtnavi/stadtnavi_app/files/6658339/car-train-1.zip)

Please wait till the icon is approved.

Make settings invisible: https://github.com/stadtnavi/digitransit-ui/issues/654

**Comment by GustavoTCh** [comment]
@Denis306 was the icon approved?

**Comment by Denis306** [comment]
Yes. Leonard approved.

**Comment by GustavoTCh** [comment]
Worked in https://github.com/trufi-association/trufi-core/pull/526
