### ISSUE TITLE
Compute both CAR and CAR_PARK for car suggestion tile

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#200]
Info on this issue: https://github.com/stadtnavi/digitransit-ui/issues/598

**Comment by GustavoTCh** [comment]
PR https://github.com/trufi-association/trufi-core/pull/521

**Comment by ahmed-nawar** [comment]
Is this feature implemented on the internal version? Because I can see there's a similar TODO task. https://github.com/stadtnavi/stadtnavi_app/issues/240

**Comment by Denis306** [comment]
@ahmed-nawar Yes. @leonardehrenfried changed the requirements so we have to rework it. once #240 is in review you can close both.
