### ISSUE TITLE
Return routes with the disabled modes in settings

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#208]
**Describe the bug**
After disabling the modes in the settings, the app returns routes with the disabled modes which is not the same behavior as the webapp.

**To Reproduce**
1. Disable all the modes in the settings
2. Plan a route

**Expected behavior**
To show a message as in the webapp `No route suggestions were found with the your settings. However, we found the following route options:`
**Screenshots**
![IMG-9530](https://user-images.githubusercontent.com/84456072/122207296-43a76600-cea2-11eb-846c-711b21ac4d1d.PNG)
![IMG-9528](https://user-images.githubusercontent.com/84456072/122207310-4904b080-cea2-11eb-8bf8-adefb315b124.PNG)
![IMG-9529](https://user-images.githubusercontent.com/84456072/122207325-4bffa100-cea2-11eb-9bc3-447f32127e87.PNG)

**Webapp**
![image](https://user-images.githubusercontent.com/84456072/122207382-5d48ad80-cea2-11eb-8617-08173334173a.png)

**Smartphone:**
 - Device: IOS

**Comment by GustavoTCh** [comment]
Resolved in this task https://github.com/stadtnavi/stadtnavi_app/issues/162
