### ISSUE TITLE
Cannot change origin or destination by clicking while in route mode 

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#209]
**To Reproduce**
1. Enter any origin and destination
2. Try to click on map to change origin or destination
3. The itinerary is changed only but you cannot click on map to view info card or change destination

**Expected behavior**
To be able to click on map while in route mode
**Screenshots**
![IMG-9530](https://user-images.githubusercontent.com/84456072/122208357-7c940a80-cea3-11eb-90b6-0349ede9ce48.PNG)

**Smartphone **
 - Device: IOS

**Comment by Denis306** [comment]
@ahmed-nawar What exactly is the behavior you want? I honestly don't get this ticket. If you go to the Google Maps app, type in destination and origin and search a route you are also not able to click on the map to change origin and destination. You do that in the Search bar.

**Comment by ahmed-nawar** [comment]
@Denis306 I confirm that in Google Maps you cannot change the origin or destination by clicking on the map when you're viewing a route. We can leave this behavior as is.
I would like to be able to click on an icon to view details about it while in route mode. example: click on a parking icon.

**Comment by Denis306** [comment]
I created a new issue #213  and am closing this one.
