### ISSUE TITLE
Add Origin / Destination Buttons to Bottom Panels

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#211]
We are still missing the origin/destination  buttons to start a navigation to POIs, etc.
![image](https://user-images.githubusercontent.com/63004289/122222217-5a55b900-ceb2-11eb-915a-4dbe8b514a41.png)

**Comment by ahmed-nawar** [comment]
Taxi POI doesn't have Origin / Destination Buttons in bottom panel.
![taxi](https://user-images.githubusercontent.com/84456072/122677913-b1c29480-d1e4-11eb-8209-9f64336afb7e.jpg)

**Comment by Denis306** [comment]
@ahmed-nawar the taxi POI does not have the origin / destination buttons in the web app either. 
![image](https://user-images.githubusercontent.com/63004289/122678058-5f35a800-d1e5-11eb-8b06-aab332c378ab.png)

@SamuelRioTz The text is still wrong though.

**Comment by hbruch** [comment]
And please note that a taxi is no cargo bike, so please fix the label

**Comment by ahmed-nawar** [comment]
> @ahmed-nawar the taxi POI does not have the origin / destination buttons in the web app either.
> ![image](https://user-images.githubusercontent.com/63004289/122678058-5f35a800-d1e5-11eb-8b06-aab332c378ab.png)
> 
> @SamuelRioTz The text in the POI of the taxi is still wrong though. It says cargo bikes at the moment.

So the buttons will not be implemented in the Taxi POI?

**Comment by Denis306** [comment]
@ahmed-nawar If wanted they can be impemented. Maybe @hbruch can say something about it?

**Comment by hbruch** [comment]
Would be in line with the other side panels, no? Medium priority

**Comment by Denis306** [comment]
As per @SamuelRioTz this is quite complex so we are leaving it out for now. But he changed the text already to be correct. So you can retest and close @ahmed-nawar.
