### ISSUE TITLE
Redesign the Menu

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#214]
![image](https://user-images.githubusercontent.com/63004289/122567648-2c56ad00-d049-11eb-84cc-2b4ff545fa55.png)

English  /  German:

Show routes  /  Verbindungen
Your places  /  Favoriten

Report defect  /  Mangel melden
Send Feedback  /  Feedback zur App

About this service  /  Über diesen Service
Social media  /  Soziale Medien
Rate the app  /  App bewerten
Share the app  /  App weiterempfehlen

Language  /  Sprachauswahl (Simply use the switching functionality we already have with the new icon)
Imprint  /  Impressum

Icons:

Show routes: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Alocation_on
Your places: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Astar_border

Report defect: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Areport
Send Feedback: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Afeedback

About this service: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Agroups
Social media: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Arss_feed
Rate the app: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Athumb_up
Share the app: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Ashare

language switcher: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Atranslate
Imprint: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aarticle

**Comment by ahmed-nawar** [comment]
Is this supposed to be already implemented on v1.3.9 ?

This is the current menu on v1.3.9
![menu](https://user-images.githubusercontent.com/84456072/122676743-9ef99100-d1df-11eb-8935-d732877acd24.png)

**Comment by Denis306** [comment]
Yes, this is already implemented. The only difference is the upper part. But it was about the menu points which got reworked. So you can close this.
