### ISSUE TITLE
Change Style of "custom leaving time" Feature

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#215]
![image](https://user-images.githubusercontent.com/63004289/122567194-b3efec00-d048-11eb-9c64-0e714579b543.png)

**Comment by GustavoTCh** [comment]
@Denis306, could you upload some screens? please

**Comment by Denis306** [comment]
@GustavoTCh we will talk in the daily about this.

**Comment by GustavoTCh** [comment]
@Denis306 Is it okey for you?
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-19 at 16 28 11](https://user-images.githubusercontent.com/42806689/122645601-642e2500-d11b-11eb-97df-778a5ca97f1d.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-19 at 16 24 31](https://user-images.githubusercontent.com/42806689/122645542-32b55980-d11b-11eb-9f17-d671df82bfa1.png)

**Comment by GustavoTCh** [comment]
Worked in https://github.com/trufi-association/trufi-core/pull/528
