### ISSUE TITLE
Text shown when sharing the app needs to be changed 

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/stadtnavi_app#219]
Current behavior: 
When the button "share the app" is clicked it shows the following text and URL which are irrelevant 

Hol' dir die stadtnavi, die App für den öffentlichen Nahverkehr in Cochabamba, auf https://appurl.io/BOPP7QnKX 

Expected behavior: 
1. The link: should link to the download link of the app from either the play store or the ios store depending on the OS 
2. The text: @Denis306 could you please write the required text if you have the info from Herrenberg? 

Environment: 
Android
Stadtnavi app 1.2.5

**Comment by Denis306** [comment]
@SamuelRioTz I will clarify what text we need and update the ticket.

**Comment by SamuelRioTz** [comment]
@Denis306 should have been fixed in the last update

**Comment by Denis306** [comment]
@SamuelRioTz Yes, I moved it to Internal so @nghanem-poet-egypt and team can check.

**Comment by nghanem-poet-egypt** [comment]
Issue is ok and will be closed
