### ISSUE TITLE
Bad request when on-demand taxi is expected 

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/stadtnavi_app#220]
**Describe the bug**
From: Seestraße 
To: Berliner Straße 28
Time 18:00 o'clock --> works correctly and shows various modes
Now change the time to 23:00 o'clock >> an error "Bad request" appears when OK is clicked the itinerary is shown but no other modes are shown
and the back button navigates outside the application 

Happens with other From addresses not only this one (check screenshots)

Expected behavior 
All possible modes should appear normally next to the first default mode and a tile should be shown for the on demand taxi 

Environment 
Android 
stadtnavi 1.2.5

**Comment by nghanem-poet-egypt** [comment]
![Screenshot_20210617-180416.jpg](https://user-images.githubusercontent.com/84389152/122435491-556b3500-cf98-11eb-9c5a-d8530b45a61e.jpg)

![Screenshot_20210617-180337.jpg](https://user-images.githubusercontent.com/84389152/122435523-5bf9ac80-cf98-11eb-9876-2a2f7c4b52b4.jpg)

**Comment by SamuelRioTz** [comment]
@GustavoTCh

**Comment by GustavoTCh** [comment]
@nghanem-poet-egypt could you check it again please? I tried to reproduce it in Android v1.3.2 (42), in this version a similar problem is already solved. this version is here https://chat.stadtnavi.eu/#narrow/stream/29-Native-Mobile.20App/topic/Current.20App.20Version/near/14879

**Comment by nghanem-poet-egypt** [comment]
Issue is solved and cannot be reproduced again neither on Internal nor on the Public version. No car route is shown anymore instead a on-demand-taxi is shown. Issue will be closed. 

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/84389152/123543471-ef786d80-d74e-11eb-95fc-2ca8b5052e30.png)
