### ISSUE TITLE
Bike and Ride displays stations twice

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/stadtnavi_app#221]
**Describe the bug**
From: Vaihingen Schillerplatz
To: Krone

Choose Bike and Ride 
The station names are shown twice the display is not like on the webapp where the name is shown only once.

Expected: can the itinerary display be like the webapp? 

**Screenshots**
Mobile 
![Screenshot_20210617-223301.jpg](https://user-images.githubusercontent.com/84389152/122469511-5498ca00-cfbd-11eb-8d4a-cfef6a9a4002.jpg)

Web 
![Screenshot_20210617-223603_Chrome.jpg](https://user-images.githubusercontent.com/84389152/122469535-5b274180-cfbd-11eb-9d09-1690e851cfce.jpg)

Android
Stadtnavi 1.2.5

**Comment by Denis306** [comment]
@GustavoTCh could you check this please? Also the "Herrenberg" besides the green "S1" train logo is missing.
