### ISSUE TITLE
Feedback User 271: redirection of rental bike URL is wrong 

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/stadtnavi_app#237]
The rental bike on the Marktplatz https://herrenberg.stadtnavi.de/fahrradstationen/fare redirects the user to a wrong website. 

current website: https://gueltsteinmobil.de/guelf-unser-lastenfahrrad
correct website: https://www.herrenberg.de/fairtrad 

This issue occurs only on the mobile app.

**Comment by leonardehrenfried** [comment]
I think the current/correct URLs are swapped but I will change it nevertheless.

**Comment by leonardehrenfried** [comment]
Hang on, are you sure that it's the one at Marktplatz, not the one in Gülststein itself? https://herrenberg.stadtnavi.de/fahrradstationen/guelf

**Comment by sara-georgy** [comment]
The issue was reported for the one at the Marktplatz and Holger has confirmed that https://www.herrenberg.de/fairtrad is the correct website.

**Comment by hbruch** [comment]
This is an app issue, not a Digitransit-issue, no?

**Comment by leonardehrenfried** [comment]
Oh, I'm in the wrong repo! Ignore me!

**Comment by sara-georgy** [comment]
yes

**Comment by Denis306** [comment]
Yes, this issue is being resolved with this ticket #119. Currently working on it.
