### ISSUE TITLE
Icons should be shown as colored dots when zoomed out

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#238]
When zooming out, the icons should only be displayed as colored dots like in the web app:
![image](https://user-images.githubusercontent.com/63004289/122756704-10484b00-d297-11eb-8938-7de07df2d173.png)

Mobile behavior right now:
![image](https://user-images.githubusercontent.com/63004289/122756762-20f8c100-d297-11eb-832b-780db6dedd81.png)

**Comment by SamuelRioTz** [comment]
https://github.com/stadtnavi/stadtnavi_app/pull/242
