### ISSUE TITLE
Car route not displayed if it's the only route

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/stadtnavi_app#241]
**Describe the bug**
If I enter 2 addresses and there is only a car route available. The car itinerary is not shown. Instead I get a grey box. 

**To Reproduce**
From: Kindergarten Erhardtstraße 
To: Nagolder Straße 
Settings: sharing is turned off

**Expected behavior**
The webapp shows car, bike and walking itineraries. It's expected that the mobile app does the same. 
[Try here](https://herrenberg.beta.stadtnavi.eu/reiseplan/Kindergarten%20Erhardtstra%C3%9Fe%2C%20Erhardtstra%C3%9Fe%202%2C%2071083%20Herrenberg%3A%3A48.593086299999996%2C8.869675666049382/Nagolder%20Stra%C3%9Fe%2C%2071083%20Herrenberg%3A%3A48.5955763%2C8.8668147?locale=de&mapMode=bicycle&time=1624003200)

**Screenshots**
First thing the message that only car routes were found
Second: the car route is shown as a grey box

![Screenshot_20210621-194535.jpg](https://user-images.githubusercontent.com/84389152/122805510-7948b680-d2c9-11eb-9838-cf7d4f1fbf81.jpg)

![Screenshot_20210621-194543.jpg](https://user-images.githubusercontent.com/84389152/122805523-7ea60100-d2c9-11eb-932a-8a4590a14a23.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung 
 - OS: Android 
 - App Version 1.2.9

**Comment by Denis306** [comment]
@SamuelRioTz @GustavoTCh could you please investigate this. It is a critical issue.

**Comment by SamuelRioTz** [comment]
@GustavoTCh

**Comment by GustavoTCh** [comment]
@Denis306 @SamuelRioTz  I review it now

**Comment by GustavoTCh** [comment]
Resolved in https://github.com/trufi-association/trufi-core/pull/535
