### ISSUE TITLE
Feedback from Ansgar: webapp and ios app have different number of available parking spaces

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/stadtnavi_app#243]
Feedback number: 281

Parking place: Oberer Graben
I've checked both parking places on the Webapp and IOS app at the time (3:16pm). Each system displayed a different number. (See Screenshots)
My assumption: the available parking spaces on the IOS app does not get updated and remains on "6 of 24 parking spaces available"

![image](https://user-images.githubusercontent.com/84382750/122932583-27a63780-d36e-11eb-8963-389ab8249993.png)
![image](https://user-images.githubusercontent.com/84382750/122932819-591f0300-d36e-11eb-8e3d-46eb74da2818.png)

**Comment by SamuelRioTz** [comment]
related with https://github.com/stadtnavi/stadtnavi_app/issues/163
