### ISSUE TITLE
Difference in suggestions between IOS & Android

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#246]
**Describe the bug**
- The ruftaxi icon is not the same.
- There is an extra walking leg on the IOS which is not there on the Android.
**To Reproduce**
1. Origin: Bahnhof Herrenberg
2. Destination: Blumenstasse 14, 71154
3. Time: 23 45
4. Check suggestions

**Expected behavior**
Same behavior in both

**Screenshots**:

IOS
![parity](https://user-images.githubusercontent.com/84456072/122962877-1e28c980-d386-11eb-8abc-2b3ad739f64e.png)
Android
![MicrosoftTeams-image (24)](https://user-images.githubusercontent.com/84456072/122962933-27199b00-d386-11eb-90ef-6c24626ff8ff.png)

**Smartphone (please complete the following information):**
 - Device: Android v1.2.9, IOS v1.3.2

Also, why is there no icon for the ondemandTaxi on the IOS

**Comment by Denis306** [comment]
@GustavoTCh connected to #247 probably.

**Comment by GustavoTCh** [comment]
@Denis306  @ahmed-nawar  I tested with IOs and Android, 

1. IOs-App : Both have the address of "Bahnhof Herrenberg", but they are two different points
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-25 at 01 06 54](https://user-images.githubusercontent.com/42806689/123343741-a5c33380-d552-11eb-8342-b48bd1ea89e8.png)

image 1:
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-25 at 01 06 43](https://user-images.githubusercontent.com/42806689/123343759-b5427c80-d552-11eb-86c8-9dc1e26aa9f5.png)

image 2:
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-25 at 01 06 25](https://user-images.githubusercontent.com/42806689/123343761-b673a980-d552-11eb-8063-a12302254ce1.png)

2. Android-App(Same result) : 

image 1:
![WhatsApp Image 2021-06-25 at 1 24 16 AM (1)](https://user-images.githubusercontent.com/42806689/123344411-1f0f5600-d554-11eb-9b0f-c2b432224235.jpeg)


image 2:
![WhatsApp Image 2021-06-25 at 1 24 16 AM](https://user-images.githubusercontent.com/42806689/123344417-20d91980-d554-11eb-95cc-e2aaf23c6347.jpeg)


WebApp(beta) same result:

image 1:
![Screen Shot 2021-06-25 at 01 03 23](https://user-images.githubusercontent.com/42806689/123344499-49611380-d554-11eb-9a86-4861ab75e99c.png)

image 2:
![Screen Shot 2021-06-25 at 01 03 02](https://user-images.githubusercontent.com/42806689/123344513-4cf49a80-d554-11eb-839a-32d2acaa1040.png)
