### ISSUE TITLE
Illogical route P&R

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/stadtnavi_app#248]
**Describe the bug**
Following the comment from @GustavoTCh https://github.com/stadtnavi/stadtnavi_app/issues/199
I found this illogical route

**What happens in the route:**
1. The user drives to a _closed_ parking
2. Then walks to a bus stop (In the _opposite_ direction of the destination)
3. Then takes a bus also in the _opposite_ direction of the destination
4. Then leaves the bus to walk in the direction of the destination

So the user will take a bus farther away from the required destination, then returns to the correct route walking.
**Expected**: The user could've parked his car then walked to the destination (which would've been faster, cheaper and less time consuming)

**To Reproduce**
https://github.com/stadtnavi/stadtnavi_app/issues/204#issuecomment-866026178

**Screenshots**
![IMG-9636](https://user-images.githubusercontent.com/84456072/122968574-f9375500-d38b-11eb-81da-39d53826253d.PNG)
![IMG-9637](https://user-images.githubusercontent.com/84456072/122968566-f76d9180-d38b-11eb-867c-b5dd855aefaa.PNG)
![IMG-9638](https://user-images.githubusercontent.com/84456072/122968555-f3417400-d38b-11eb-848f-ec9cf331b21a.PNG)

**Smartphone:**
 - Device: IOS v1.3.2

**Additional context**
~~The fact that the route parked the car in a closed parking still under investigation~~

**Comment by Denis306** [comment]
@ahmed-nawar This is a backend bug.

As far as communicated yesterday during the Sprint Change, this is a backend issue that @leonardehrenfried is already working on. Right?

**Comment by leonardehrenfried** [comment]
Yes, and no. We want to exclude it but we don't know if we will manage.

**Comment by ahmed-nawar** [comment]
Will we create a backend ticket for this issue? @leonardehrenfried

**Comment by Denis306** [comment]
@leonardehrenfried should we close this here or do you want to keep it? I already labeled It with "Backend" so we know it is not on the mobile App side.

**Comment by leonardehrenfried** [comment]
yes

**Comment by ahmed-nawar** [comment]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Gipswerkstra%C3%9Fe%2011%2C%2071083%20Herrenberg%3A%3A48.5747331217215%2C8.915791511535646/Osteria%20da%20Gino%2C%20Bronngasse%201%2C%2071083%20Herrenberg%3A%3A48.59600105%2C8.86991460672521/parkAndRide/?locale=en&time=1624963078

Another scenario with weird P&R suggestion
![image](https://user-images.githubusercontent.com/84456072/123787507-31ceb580-d8db-11eb-9114-0656b90e6740.png)
