### ISSUE TITLE
Add fare information disclaimer

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/stadtnavi_app#249]
In the web app we added a disclaimer about the fare information.

![Screenshot from 2021-06-23 11-09-46](https://user-images.githubusercontent.com/151346/123071347-e026b680-d414-11eb-9025-76260920d4ba.png)

Please also add this disclaimer.

You might also find this commit useful, which contains the German and English translation: https://github.com/stadtnavi/digitransit-ui/commit/5033f49e7e009c09023b4987e2cdf34bb556b984

**Comment by ahmed-nawar** [comment]
The fares are not shown. IOS v1.3.7
