### ISSUE TITLE
Road closure not recognizable

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/stadtnavi_app#263]
**Describe the bug**
The no-through-symbol of road closures has not a white fill, but a transparent one. Thus it is barely recognizable as road closure.

**To Reproduce**
1. Go to aa road closure and see the rendered road closure

**Screenshots**
![image](https://user-images.githubusercontent.com/2187389/123532845-1152ff80-d711-11eb-9b07-d60e83227162.png)

**Desktop (please complete the following information):**
 - OS: iOS

**Comment by Denis306** [comment]
@SamuelRioTz This issue should be resolved with #184 right? If not, please give the Road closure signs a white filling instead of it being transparent.
