### ISSUE TITLE
bike & ride option does not render take bike on transit

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/stadtnavi_app#272]
**Describe the bug**
Bike & Ride options don't show take your bike on transit in trip overview

**To Reproduce**
1. Search trip from Herrenberg to Stuttgart
2. Click on bike & ride tab
3. See bike & park & transit option
4. See bike & transit option (neither parking nor take bike on transit shown)

**Expected behavior**
Bike & take biike on transit should be displayed as in webapp.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2187389/123748274-48ade180-d8b4-11eb-9890-7862c0f55008.png)

**Comment by GustavoTCh** [comment]
implemented in https://github.com/trufi-association/trufi-core/compare/feat/adding-bike-to-public-transport?expand=1
