### ISSUE TITLE
Rework the bike sharing itinerary leg

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#276]
Currently the mobile app displays too little information in the bike sharing itinerary legs:
![image](https://user-images.githubusercontent.com/63004289/123800106-3a2ded00-d8e9-11eb-9634-bcb61cfec6b9.png)

Compared to that, the web app shows a lot more information on the bike sharing leg. Like the name of the stations, availability indicator, and the info box. 
![image](https://user-images.githubusercontent.com/63004289/123800241-5fbaf680-d8e9-11eb-90da-bc6415a9fa76.png)

You can see in this itinerary:
https://dev.stadtnavi.eu/reiseplan/Herrenberg%3A%3A48.595557%2C8.8674715/Stuttgart%3A%3A48.7784485%2C9.1800132/0?time=1624970411

**Comment by GustavoTCh** [comment]
Implemented in https://github.com/trufi-association/trufi-core/pull/558
