### ISSUE TITLE
Addresses are being listed twice in the search

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#316]
![image](https://user-images.githubusercontent.com/63004289/204029183-5a0f21b8-254f-4720-ad1d-4c04b5375c1f.png)

**Comment by GustavoTCh** [comment]
@Denis306 @SamuelRioTz, EndPoint returned 2 similar data for query "bahnhof" (first 2 values), I checked the [request](https://photon.stadtnavi.eu/pelias/v1/search?text=bahnhof&boundary.rect.min_lat=48.34164&boundary.rect.max_lat=48.97661&boundary.rect.min_lon=9.95635&boundary.rect.max_lon=8.530883&focus.point.lat=48.5957&focus.point.lon=8.8675&lang=de&sources=oa,osm,gtfshbg&layers=station,venue,address,street) and in the same situation the server returned the same response.

![Screen Shot 2022-11-29 at 17 46 07](https://user-images.githubusercontent.com/42806689/204654882-013a4c16-ff78-4f43-a422-bc3fa9bfb454.png)

Apparently the web does some extra processing to filter the results.
