### ISSUE TITLE
Possibility to edit Push-notification - any news?

### ISSUE THREAD

**Issue by stadtnavimanager** [stadtnavi/stadtnavi_app#330]
@Denis306 (sorry, ich kann leider nicht nachträglich assignen, scheint mir, LG Jana)

**Comment by Denis306** [comment]
@stadtnavimanager Ich würde das Ticket hier schließen, oder was meintest du damit?

**Comment by stadtnavimanager** [comment]
@Denis306 ja, das hat sich mit dem aktuellen Auftrag erledigt
