### ISSUE TITLE
Parking information list (Parkhausinformationsliste) is not loading

### ISSUE THREAD

**Issue by Benedikt-LB** [stadtnavi/stadtnavi_app#334]
The parking information list is not working on both systems (iOS and Android) in the Ludwigsburg App.

PS: Still cant add labels to the issue.

**Comment by Jasmin-LB** [comment]
The problem described by Benedikt on Feb 8, 2023, occurred again yesterday (Jul 14, 2024) and still exists.

![LB 1_1](https://github.com/user-attachments/assets/2193875c-c9e4-4ce3-93d0-f36792f0b6fa)
![LB 1_2](https://github.com/user-attachments/assets/9eb2dc8b-9fa5-46c4-b4ec-3b199e1a36f9)
