### ISSUE TITLE
Wrong distance (Km) Number

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#350]
Is your feature request related to a problem? Please describe.
The distance / amount of km for the route from "Herrenberg" to "Merklingen - Schwäbische Alb" is too big. 
![image](https://github.com/stadtnavi/stadtnavi_app/assets/63004289/8b0a9e8d-d432-4e68-b541-584d5a9de24f)

Describe the solution you'd like
Investigate why the number is so big and implement the fix so it is displayed the same way like in the web app.

Additional context
stadtnavi Web App Screenshot:
![image](https://github.com/stadtnavi/stadtnavi_app/assets/63004289/4c62d938-1607-4495-a7c4-91d8b214e582)

**Comment by GustavoTCh** [comment]
I resolved this in Feat/implement improves #349
I have transferred the distance data from the preview itineraries to the details view like WebApp.

![Screenshot_1699904973](https://github.com/stadtnavi/stadtnavi_app/assets/42806689/46ee6c0e-37cd-498d-9ca5-d609b5fbbc33)

![Screenshot_1699904860](https://github.com/stadtnavi/stadtnavi_app/assets/42806689/1fe626f5-dfbb-440e-8df4-894aa1786380)

**Comment by hbruch** [comment]
Is this still open @Denis306 ?
