### ISSUE TITLE
Investigate Parking Indicators on OTP2.4

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#351]
THe parking indicators in the application are not working properly with OTP2.4.

**Comment by GustavoTCh** [comment]
Resolved the issue, with otp 2.4
![Screenshot_1699900161](https://github.com/stadtnavi/stadtnavi_app/assets/42806689/3fe01e86-599b-46a7-8dbc-c4a57f797794)

![Screenshot_1699900152](https://github.com/stadtnavi/stadtnavi_app/assets/42806689/23abfe48-5221-405e-b29e-bd25a04c5dc5)

**Comment by hbruch** [comment]
On sunday, all parkings are shown in the with closed badge, though they are open.
Please compare with the digitransit webapp, which shows correct behavior.

![24E82B68-A060-4E7D-91C9-1CE4AFA4AE41](https://github.com/stadtnavi/stadtnavi_app/assets/2187389/dfec0874-147f-43bd-a8fd-3da6ffbe54cb)

**Comment by Denis306** [comment]
Done
