### ISSUE TITLE
Enable In-App-Messages

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#359]
- [x] Research SDK and configuratio parameters 
- [x] stadnavi core implementation to use in-app-messages functionality
- [x] Apply configurations to stadtnavi Herrenberg
- [x] Add an "x" button at the top right corner to close the notification once opened in the app.
- [x] Create Event for daily opening of Survey Use Case
- [x] Testing
- [x] Messages are not being sent to the production environment.

**Comment by GustavoTCh** [comment]
@stadtnavimanager 
I’ve made improvements and resolved bugs related to In App Notification in version 1.9.2:

1. For In-App Messages, Firebase does not allow changing the behavior of popups, so we cannot make custom modifications. However, this is possible with Push Notifications.

2. I created two events for daily notifications: one for iOS, called “EveryDay InAppNotification iOS,” and another for Android, called “EveryDay InApp.”

**Comment by GustavoTCh** [comment]
@Denis306 @stadtnavimanager
In-app notifications are working in production.

**Comment by Denis306** [comment]
@GustavoTCh thank you!
@stadtnavimanager if everything is done and tested from your side, feel free to close this issue with a comment.

**Comment by stadtnavimanager** [comment]
@GustavoTCh @Denis306 Thank you for the implementation!
Unfortunately I cannot close the issue - maybe I need to apply for a different role?
feel free to close the issue and please remember the documentation-part

**Comment by Denis306** [comment]
@stadtnavimanager Thank you! The documentation will be done in this issue #360.
