### ISSUE TITLE
Integrate with the Stadtnavi MapTiler

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#39]

**Comment by SamuelRioTz** [comment]
@leonardehrenfried until now we were using a temp MapTiler key, for this feature we will need the stadtnavi mapTileUrl,
I already tried to use **https://tiles.stadtnavi.eu/streets/{z}/{x}/{y}.png** but I got unauthorized error.
We need a mapTileUrl template for each map type

**Comment by SamuelRioTz** [comment]
@leonardehrenfried  This is the current config for Map Tile images
streets:
`urlTemplate: "https://tiles.stadtnavi.eu/streets/{z}/{x}/{y}.png"`
satellite:
 `urlTemplate: "https://api.stadtnavi.de/tiles/orthophoto/{z}/{x}/{y}.jpg"`
`urlTemplate: "https://tiles.stadtnavi.eu/satellite-overlay/{z}/{x}/{y}.png"`
bike:
`urlTemplate:"https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png"`
`subdomains: ["a", "b", "c"]`

but in the app the map tile images quality is too low, it could be possible to provide map tile images on high definition.

> e.g. from 256x256 to 521x521

![image](https://user-images.githubusercontent.com/43000324/117829444-c2283c80-b240-11eb-8c53-8affec07cedb.png)

**Comment by leonardehrenfried** [comment]
For our own tile server you can use the following URL for hi-res tiles:

```
https://tiles.stadtnavi.eu/streets/{z}/{x}/{y}@2.png
```

CycloOSM and the Orthophoto layer unfortunately doesn't have a high res version.
