### ISSUE TITLE
Compared to stadtnavi web: different routing suggestions are displayed in the ios app 

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/stadtnavi_app#41]
**Describe the bug**
The IOS app displays different routing suggestions other than the web app

**To Reproduce**
1. Go to 'https://herrenberg.qa.stadtnavi.eu/'
2. Start: Kreiskrankenhaus
3. Ziel: Fahrradparkplatz Bahnhof Herrenberg
4. Only routing suggestion is displayed
5. Open the ios app and type the same data
6. More than one routing suggestion is made for the same combination

**Expected behavior**
The IOS app and the web app should display the same results

**Screenshots**
![Stadtnavi web different routing suggestions](https://user-images.githubusercontent.com/83356918/117725143-05ed5880-b1e5-11eb-9a2c-da39e39cebc0.png)
![IOS app different routing suggestions](https://user-images.githubusercontent.com/83356918/117725169-0d146680-b1e5-11eb-82ef-9371397b339b.jpeg)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser: chrome
 - Version: 90.0.4430.85

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: 13.1.2
 - mobile test application: stadtnavi
 - Version: 1.0.2

**Comment by GustavoTCh** [comment]
@samia-roubaa we are working in the development environment and not in the QA environment, but now the serverDev returns us the same route.

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-05-14 at 13 42 55](https://user-images.githubusercontent.com/42806689/118308782-5cdf8000-b4ba-11eb-97a6-73962542650c.png)

**Comment by SamuelRioTz** [comment]
@Denis306 could you verify if this ticket is still valid
