### ISSUE TITLE
Change the "Team" Tab in the menu to "Imprint"

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#44]
Change the Team tab in the app to imprint and move it to the bottom of the menu underneath the social media tabs.
![image](https://user-images.githubusercontent.com/63004289/117827856-a0937900-b271-11eb-9041-983016ea464f.png)

Also use the impressum of the city of Herrenberg:
https://www.herrenberg.de/impressum

**Comment by GustavoTCh** [comment]
@Denis306 I need more description about content, Is Impressum tab a linker to https://www.herrenberg.de/impressum? or Is a page with data about contributing organizations?
