### ISSUE TITLE
Itinerary not working properly

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#59]
from gärtringen to nufringen, on May 5th 5:30pm, when enabling bike sharing, it only shows one bike-only route/itinerary, instead of a) public transport options as well, and b) intermodal bike + public transport options

**Comment by GustavoTCh** [comment]
I  fixed Trufi-Core https://github.com/trufi-association/trufi-core/pull/471

We have the same result as in [DevStadtnavi](https://dev.stadtnavi.eu/reiseplan/G%C3%A4rtringen%3A%3A48.6419208%2C8.9031632/Nufringen%3A%3A48.6224388%2C8.8881021/?locale=en&time=1621330200), we have repeated routes, but this is already part of another ticket-task in the board.

![Screen Shot 2021-05-17 at 23 26 49](https://user-images.githubusercontent.com/42806689/118586816-68a49e00-b769-11eb-9e30-78660e8aaca5.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-05-17 at 23 27 04](https://user-images.githubusercontent.com/42806689/118586828-6e01e880-b769-11eb-849d-1d3be6f81cc3.png)
