### ISSUE TITLE
Timing of the routing suggestion is missing

### ISSUE THREAD

**Issue by samia-roubaa** [stadtnavi/stadtnavi_app#69]
**Describe the bug**
The timing of the routing suggestion is not shown like the web app.
Only the duration of the route is shown and that is not sufficient.

**To Reproduce**
1. Go to 'https://herrenberg.beta.stadtnavi.eu/'
2. Start: Neubau ALDI und Wohnungen
3. Ziel: Neubau ALDI und Wohnungen
4. The web app will show the suggested routings. Each suggestion shows the timing (when to start - when to end) and the duration of the route.
![image](https://user-images.githubusercontent.com/83356918/119257605-47f3a280-bbc6-11eb-8267-5af82d5927c5.png)

5. Open the IOS app
6. repeat Step 2 and 3
7. The app will show the suggested routings
8. The app only shows the duration of the route

**Expected behavior**
The mobile app should also show the timing of the routing suggestion (when to start - when to end) as this information is critical. The duration of the route is not enough.

**Screenshots**
![image](https://user-images.githubusercontent.com/83356918/119257717-d1a37000-bbc6-11eb-9db0-244f2e99a2b8.png)
![image](https://user-images.githubusercontent.com/83356918/119257731-dec05f00-bbc6-11eb-8445-601da69da171.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 premium
 - Browser: Chrome
 - Version: 90.0.4430.85
**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS14.4
 - Stadtnavi app
 - Version: 1.1.0

**Comment by Denis306** [comment]
Closing this as it is the same as issue #14

**Comment by Denis306** [comment]
Closing this as it is the same as issue #14
