### ISSUE TITLE
Address not displayed when selecting origin or destination with the "Choose on map" function.

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#80]
When selecting an origin or a destination with the "Choose on map" function, or by a long tap on the map the search bar doesn't display the address but rather "Map Marker". 

Please change this so that the search bar displays the address of the location the map marker is pointed at.
![image](https://user-images.githubusercontent.com/63004289/119644832-a5356100-be1d-11eb-9f87-352e3dce2bc1.png)

**Comment by Denis306** [comment]
@leonardehrenfried @hbruch which endpoints can we use to implement this?

**Comment by leonardehrenfried** [comment]
Example: https://photon.stadtnavi.eu/pelias/v1/reverse?point.lat=48.59050387249519&point.lon=8.865580558776857&boundary.circle.radius=0.1&lang=de&size=1&layers=address&zones=1
