### ISSUE TITLE
POI layers shown in mobile app are not the same as webapp

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/stadtnavi_app#88]
**Describe the bug**
There are big differences between the mobile app and the webapp when I click on "Show on map" icon 
![grafik](https://user-images.githubusercontent.com/84389152/119652125-03fed880-be26-11eb-8a90-25cce5011804.png)

Not only the names are different but also there are missing items in the mobile app for example "Bus terminals" exists in webapp but not on mobile. and "Parking spot" exists in mobile app but not in webapp. 
 

**To Reproduce**
Click on "show on map" in the webrowser and the same in the mobile app

**Expected behavior**
Both should have the same list of shown POI on the map. Assuming the webapp has the correct list, then the mobile app should have the same list. 

**Screenshots**
![show on map mobile](https://user-images.githubusercontent.com/84389152/119653048-29d8ad00-be27-11eb-9d93-33481d13d3e9.png)
![show on map mobile 2 png](https://user-images.githubusercontent.com/84389152/119653054-2ba27080-be27-11eb-8fef-9d2f1d92ceb7.png)
![20210526 13_35_42-Window](https://user-images.githubusercontent.com/84389152/119653171-4e348980-be27-11eb-8908-c258407007e7.png)

**Desktop (please complete the following information):**
 - Browser Firefox used for comparison on PC

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A52
 - OS: Android 11

**Comment by Denis306** [comment]
@nghanem-poet-egypt could you please verify this ticket again? I think this was tested on an old version and should be fixed by now.

**Comment by nghanem-poet-egypt** [comment]
@Denis306  I validated it again and noticed the following: 
- the order is not the same, I think it is more usable if they appear in the same order and same grouping
- In the mobile app "Fahrradparkplätze" appears twice and "Busbahnhöfe" is missing

![MicrosoftTeams-image](https://user-images.githubusercontent.com/84389152/121005014-a22c6000-c78f-11eb-943e-2c85b0e8df18.png)

**Comment by Denis306** [comment]
@nghanem-poet-egypt as the map layer is currently being reworked, I will change this Issue to only the "Fahrradparkplätze" topic if it is okay for you.

**Comment by nghanem-poet-egypt** [comment]
No problem, that's ok is it being tracked in this issue https://github.com/stadtnavi/stadtnavi_app/issues/124 ?

**Comment by Denis306** [comment]
@nghanem-poet-egypt  Closing this as it is resolved.
