### ISSUE TITLE
Enhance the Favorites functionalty

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#9]
In the Trufi App you can "heart" a location to add it to your favorites.
<img width=200 src="https://user-images.githubusercontent.com/63004289/116935488-b77d0e80-ac66-11eb-9eea-3ee1798b3958.png">

These Favorites should also be displayed in the "your places" tab so that you can edit them, add an icon or delete them.
<img width=200 src="https://user-images.githubusercontent.com/63004289/116935588-d67ba080-ac66-11eb-9410-494b6cf4e852.png">

**Comment by GustavoTCh** [comment]
https://github.com/trufi-association/trufi-core/pull/455 this is the PR in Trufi-Core
