### ISSUE TITLE
App doesn't show public transportation options and no car options in some cases

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/stadtnavi_app#90]
**Issue number 1:** 
After many trials with From and To addresses, the routing options I get **never include public transportation** options. Below is an example: 

From: Bahnhof Herrenberg, Bahnhofstraße 14, 71083 Herrenberg
To: Lupinenweg, 71083 Herrenberg

--> The mobile app shows the route by car as default route. If car is turned off from the settings, the app shows bike or walking, **never** the bus.
--> However the web app shows the route by bus as default route [Try here](https://herrenberg.qa.stadtnavi.eu/reiseplan/Bahnhof%20Herrenberg%2C%20Bahnhofstra%C3%9Fe%2014%2C%2071083%20Herrenberg%3A%3A48.593861700000005%2C8.86307270000001/Lupinenweg%2C%2071083%20Herrenberg%3A%3A48.6088722%2C8.8603017?time=1622027411)

Expected behavior: With all settings equal the mobile app should show the same routing options as the webapp assuming the webapp is correct. 

**Issue number 2:** 

Use same Addresses from the issue before and turn off the option "Carpool" from the settings but turn on the option "Car" from the settings .
Current behavior: not even the car route is shown although the "Car" mode is turned on. Only the bike route is shown. 
Expected behavior: the Car route should be shown. 

Desktop (please complete the following information):
    Browser Firefox used for comparison on PC

Smartphone (please complete the following information):
    Device: Samsung Galaxy A52
    OS: Android 11

**Comment by Denis306** [comment]
@nghanem-poet-egypt could you please re test this and close the issue? This should be fixed in the current version as per my testing.
![image](https://user-images.githubusercontent.com/63004289/122790693-dbe58680-d2b8-11eb-90d6-c9352f26eb88.png)

**Comment by nghanem-poet-egypt** [comment]
Yes it works now, issue will be closed
