### ISSUE TITLE
Reporting Issue Button not working 

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/stadtnavi_app#96]
**Describe the bug**
- When I click on the button "report and issue" an error appears (see screenshot)

**Expected behavior**
The feedback form should open

**Screenshots**
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/84389152/120103982-881ccd00-c152-11eb-9623-154a5b5e75f4.png)

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android
 - Version:1.1.2

**Comment by Denis306** [comment]
@nghanem-poet-egypt Closing this as it is resolved. The feedback botton doesn't exist on the map anymore. It is now in the menu.

**Comment by nghanem-poet-egypt** [comment]
@Denis306 unfortunately the same behavior happens even when I click on it in the menu. it shows me the message "Die Feedback App konnte nicht geöffnet werden.... ". Is there already a ticket for that? If not, is it ok if I reopen this one again?

**Comment by Denis306** [comment]
@nghanem-poet-egypt which environment are you testing on? Android? iOS? I have the app open and for me it is working?

**Comment by nghanem-poet-egypt** [comment]
Android on the internal app--- Wait, it is working now. It was not working because I didn't have the location permission granted for the app. 
But why is the behavior like that?

**Comment by Denis306** [comment]
That's how it was implemented. 
In the web app you have to put in information about the location of the defect. And as it is more userfriendly on the phone and the web app also uses automatic location recognition we used that as well.
![image](https://user-images.githubusercontent.com/63004289/122743954-d1f75f80-d287-11eb-8658-044a4f45acb4.png)
